name: Test Release to NPM

on:
  workflow_dispatch:
    inputs:
      version_suffix:
        description: 'Version suffix (e.g., test1, alpha1)'
        required: true
        default: 'test1'

jobs:
  test-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'

      - name: Install dependencies
        run: |
          yarn install --prefer-offline --pure-lockfile || yarn install

      - name: Build packages
        run: yarn build

      - name: Update version for testing
        run: |
          # Get current version
          CURRENT_VERSION=$(node -p "require('./packages/client/package.json').version")
          TEST_VERSION="${CURRENT_VERSION}-${{ github.event.inputs.version_suffix }}"
          
          # Update client version
          cd packages/client
          npm version $TEST_VERSION --no-git-tag-version
          
          # Update server version
          cd ../server
          npm version $TEST_VERSION --no-git-tag-version

      - name: Publish test version to NPM
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd packages/client
          npm publish --tag test
          
          cd ../server
          npm publish --tag test

      - name: Show installation command
        run: |
          TEST_VERSION=$(node -p "require('./packages/client/package.json').version")
          echo "🎉 Test packages published!"
          echo ""
          echo "Install with:"
          echo "npm install @react-native-live-context/client@test"
          echo "npm install @react-native-live-context/server@test"
          echo ""
          echo "Or specific version:"
          echo "npm install @react-native-live-context/client@$TEST_VERSION"
          echo "npm install @react-native-live-context/server@$TEST_VERSION"